// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nlzhvwwbqluuoubytuit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5semh2d3dicWx1dW91Ynl0dWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2ODA2MTIsImV4cCI6MjA3NjI1NjYxMn0.fSJrtzrjybj8NlbuAsBDEYEfC15Jwg9muXuECa1Pjtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);